const testPrices = [
  [
    "Dengue Test price",
    "Dengue NS1 Antigen Test price",
    "Vitamin B12 Test price",
    "Vitamin D Test price",
    "Lipid Profile Test price",
    "Dengue NS1 Antigen Test price",
  ],
  [
    "Smear for Malarial Parasite",
    "Creatinine Test price",
    "Free Thyroid Profile Test price",
    "Electrolytes Test price",
    "Testosterone Test price",
    "Anti-TPO Antibody Test price",
    "CA 125 Test price",
  ],
  [
    "AMH Test price",
    "HIV Test price",
    "PPBS Test price",
    "Iron Profile Test price",
    "Typhidot Test price",
    "Ferritin Test price",
  ],
  [
    "Urine Culture Test price",
    "TSH Test price",
    "Urine Routine Test price",
    "Platelet Test price",
    "Beta hCG Test price",
    "FBS Test price",
  ],
  [
    "Thyroid Function Test price",
    "Liver Function Test price",
    "Kidney Function Test price",
    "HBA1c Test price",
    "CBC Test price",
    "CRP Test price",
  ],
];

const PopularTests = [
  [
    "AMH Test",
    "BUN Test",
    "CBC Test",
    "Chlamydia Test",
    "Cholesterol Test",
    "Creatinine Test",
    "CRP Test",
  ],
  [
    "Thyroid Test",
    "Uric Acid Test",
    "Urine Culture Test",
    "VDRL Test",
    "Vitamin B12 Test",
    "Vitamin D Test",
    "Widal Test",
  ],
  [
    "PPBS Test",
    "Prolactin Test",
    "RAST Test",
    "RBS Test",
    "RT PCR Test",
    "SGPT Test",
  ],
  [
    "HIV Test",
    "KFT Test",
    "LFT Test",
    "Lipid Profile Test",
    "PCOD Test",
    "PCOD Test",
  ],
  [
    "CRP Test",
    "D Dimer Test",
    "Dengue Test",
    "ESR Test",
    "FBS Test",
    "Hba1c Test",
  ],
];
const footer = {
  Company: [
    "About Us",
    "Careers",
    "Blogs",
    "Contact Us",
    "NABL Data",
    "Responsible Disclosure",
  ],
  Partners: ["For Doctors", "For Corporates"],
  "Lab tests across India": [
    "Lab test in Bengaluru",
    "Lab test in Gurugram",
    "Lab test in Delhi",
    "Lab test in Noida",
    "Lab test in Hyderabad",
    "Lab test in Mumbai",
  ],
  "Health checkups across India": [
    "Full Body Checkup in Bangalore",
    "Full Body Checkup in Gurugram",
    "Full Body Checkup in Delhi",
    "Full Body Checkup in Noida",
    "Full Body Checkup in Hyderabad",
    "Full Body Checkup in Mumbai",
  ],
};

export { testPrices, PopularTests, footer };
